name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Upload deployment files
        run: scp -o StrictHostKeyChecking=no -r ./* root@157.173.222.223:/root/test-applicaion/ph-testy-app/ph-testy-treat-client/

      - name: Run deployment commands
        run: |
          ssh -o StrictHostKeyChecking=no root@157.173.222.223 << 'EOF'
          set -e  # Exit immediately if a command exits with a non-zero status
          cd /root/test-applicaion/ph-testy-app/ph-testy-treat-client/
          npm install
          npm run build
          # Restart services or perform other deployment tasks if needed
          # Example: pm2 restart all
          EOF
