name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Deploy application
        run: |
          ssh -o StrictHostKeyChecking=no root@157.173.222.223 << 'EOF'
            # Navigate to the application directory
            cd /root/test-applicaion/ph-testy-app/ph-testy-treat-client/

            # Pull the latest code from the repository
            git pull origin main

            # Install dependencies (if needed)
            npm install

            # Build the application (if needed)
            npm run build

            # Restart the application
            # Replace this with the command to restart your app (e.g., PM2, systemd)
            pm2 restart all
          EOF
